version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: camera
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Spring Boot Application
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/camera
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
      JWT_SIGNING_KEY: 31abd06668eb8056f3055780397d9d46f61ef217564ab896de4fa7c95742d2c2d6b14cc324c169a96527acd2cb73e728cb6b8cf4661552450051fafd7389b7fd814dd49f87c851aa233f063215e972b5d494108840ec5b26f0acc980d9197c355ebee669548d54ce3f191f59d90f6eba46430279dd895da49fdf20a59b9e0bb51ce66357d995a43afc8ab3ca8b23de95e991b4f8c43462ee2f3a2f1974c411df28be597d9ae25648145d49785379a35cacd7d8fb8021204e896fa24f1e1ab97b084fb58990e43baf5322949aef5da0b0aafc18207baeb7771f824bdc544173b28ab6259db60ab16e9c27c2767e41fe3cd5db7065d4705f17de8c4e5b4bc62654
      JWT_HEADER_STRING: Cookie
      JWT_AUTHORITIES_KEY: roles
      JWT_TOKEN_VALIDITY: "3600000"
      APP_MAX_FILE_SIZE: "10485760"
      MOVIE_FILE_UPLOAD_DIRECTORY: /app/uploads
    volumes:
      - uploads:/app/uploads

  # # Angular Application (if applicable)
  # frontend:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   container_name: angular_app
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend

# Volumes for persistent data
volumes:
  postgres_data:
  uploads:
