server:
  port: ${PORT:8080}

spring:
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
  web:
    resources:
      static-locations: ${STATIC_LOCATION}
  
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  security:
    user:
      password: ${SPRING_SECURITY_USER_PASSWORD}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  header:
    string: ${JWT_HEADER_STRING}
  signing:
    key: ${JWT_SIGNING_KEY}
  authorities:
    key: ${JWT_AUTHORITIES_KEY}
  token:
    validity: ${JWT_TOKEN_VALIDITY}

logging:
  level:
    ma:
      cinecamera:
        security: ${LOGGING_LEVEL_SECURITY}
    org:
      springframework: ${LOGGING_LEVEL_SPRINGFRAMEWORK}

app:
  max-file-size: ${APP_MAX_FILE_SIZE}

movie:
  file:
    upload:
      directory: ${MOVIE_UPLOAD_DIR}

youcanpay:
  public-key: ${YOUCANPAY_PUBLIC_KEY}
  private-key: ${YOUCANPAY_PRIVATE_KEY}
