package ma.cinecamera.model.enums;

public enum Genre {
	ACTION, ADVENTURE, ANIMATION, BIOGRAPHY, COMEDY, CRIME, DOCUMENTARY, DRAMA, FAMILY, FANTASY, HISTORY, HORROR,
	MUSICAL, MYSTERY, ROMANCE, SCIENCE_FICTION, SPORTS, THRILLER, WAR, WESTERN

}
